name: samsblog
favicon: null
layout_spectrum: 0.90364
typography_spectrum: 0.981012140866369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5
  lightness: 0.18493351223878562
  saturation: 0.09235462942160666
  rhythmicContrast: 0.4935162295587361
purpose: []
