name: samsblog
favicon: null
layout_spectrum: 0.90364
typography_spectrum: 0.81533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfe9f8'
    - '#8ec6e9'
    - '#22697d'
    - '#5186c8'
    - '#0c3a6e'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
